spring.application.name=auth-service

# ======= SERVER CONFIG =======
server.port=8081

# ======= DATASOURCE CONFIG =======
spring.datasource.url=jdbc:mysql://localhost:3306/eco_auth_db?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

# ======= JPA / HIBERNATE CONFIG =======
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

# ======= GENERAL SETTINGS =======
spring.mvc.pathmatch.matching-strategy=ant_path_matcher
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jackson.serialization.WRITE_DATES_AS_TIMESTAMPS=false
